### ISSUE TITLE
Add missing 1.4.1 addresses for official supported networks. 

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#1046]
# What is needed?
Add the 1.4.1 addresses to this project for official supported networks https://docs.safe.global/core-api/transaction-service-supported-networks.

**Comment by wongtsejian** [comment]
I would like to second this proposal. Please add v1.4.1 support for Avalanche C-Chain.

**Comment by moisses89** [comment]
@safe-global/safe-protocol 
The following networks have not 1.4.1 contracts deployed:
- Aurora
- Zksync
- Scroll (L2 contract is not deployed)
- X-Layer

**Comment by nlordell** [comment]
Scroll deployments should be ready: https://github.com/safe-global/safe-deployments/pull/637
I'm a bit stuck on Aurora deployments, the transactions aren't going through for some reason...
