### ISSUE TITLE
[New chain]: Avalanche C-Chain

### ISSUE THREAD

**Issue by wongtsejian** [safe-global/safe-eth-py#1047]
### Summary

I would like to add v1.4.1 safe smart contract singleton and proxy addresses to the repo. 

### Chain ID

43114

### Chain detail URL

https://chainlist.org/chain/43114

### RPC URL

https://1rpc.io/avax/c

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x6e5ad457d0f942acd4789bbb8582663aaae6acfa7a30795abe6eeda8d01a7d1f

### Block explorer URL (Master copy)

https://snowtrace.io/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0xba3776597a6986b6dd977c9f842ff03e3eb493779593d4f4c1dbb3b7e1aec256

### Block explorer URL (Master copy L2)

https://snowtrace.io/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0x2c621011f2c3111a5837e511eefdc186da2c339608a64c9264441bc76f7a1cb3

### Block explorer URL (Proxy factory)

https://snowtrace.io/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by wongtsejian** [comment]
The deployment information can be found here: https://snowtrace.io/tx/0x6e5ad457d0f942acd4789bbb8582663aaae6acfa7a30795abe6eeda8d01a7d1f

@falvaradorodriguez could you help to check why was there validation errors? Thank you.

**Comment by wongtsejian** [comment]
It seems to be an rpc issue. Validation passed after switching to another public rpc.

**Comment by moisses89** [comment]
Issue related with #1046
