### ISSUE TITLE
Update ENS Subgraph URL

### ISSUE THREAD

**Issue by gskril** [safe-global/safe-eth-py#1061]
The ENS subgraph URL used in this repo (`https://api.thegraph.com/subgraphs/name/ensdomains/ens`) will have a global rate limit added on June 12. To avoid this, it is recommended to create your own API key with TheGraph.

It’s free for the first 100k requests/month, and the ENS DAO Ecosystem Working Group is offering potential sponsorships if you go beyond that. [Here is a video](https://www.loom.com/share/a03ca8bc85624134bc7344a199200f0b) walking through the setup process (less than 5 mins).

This is due to [TheGraph sunsetting its hosted service](https://thegraph.com/docs/en/sunrise/). The old URL will begin serving requests from an ENS DAO-sponsored API key, so **this is not a breaking change** for ENS, but it will introduce a more restrictive rate limit.

---

The hosted subgraph is used here: https://github.com/safe-global/safe-eth-py/blob/main/gnosis/eth/clients/ens_client.py#L24

**Comment by fmrsabino** [comment]
Hey @gskril ! Thanks for raising this issue. We have decided to remove the default configuration that our `EnsClient` had.

This ultimately means that the configuration is delegated to the consumers of `safe-eth-py` – users of the library would have more context on which configuration to use and the respective limits tied to that configuration.

This new change is now available in the following release https://github.com/safe-global/safe-eth-py/releases/tag/v6.0.0b32
