### ISSUE TITLE
[New chain]: Bevm Mainnet 1.4.1

### ISSUE THREAD

**Issue by icodezjb** [safe-global/safe-eth-py#1190]
### Summary

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-11501.json
https://github.com/safe-global/safe-deployments/pull/672

### Chain ID

11501

### Chain detail URL

https://chainlist.org/chain/11501

### RPC URL

https://rpc-mainnet-1.bevm.io

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x10847677a61bce24e197772980fc0ae9e35c7eb35b4f086809f68c0fcf6cabf7

### Block explorer URL (Master copy)

https://scan-mainnet.bevm.io/tx/0x10847677a61bce24e197772980fc0ae9e35c7eb35b4f086809f68c0fcf6cabf7

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0xd5cede7347142e6fe15db4fd4d741a9ead0acdf4cd6f1da1d2a1ee2f0893d71c

### Block explorer URL (Master copy L2)

https://scan-mainnet.bevm.io/tx/0xd5cede7347142e6fe15db4fd4d741a9ead0acdf4cd6f1da1d2a1ee2f0893d71c

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xc39162a5b81375e7713d248591290f84fdbed32c86498b0e99dfd6c52a935c05

### Block explorer URL (Proxy factory)

https://scan-mainnet.bevm.io/tx/0xc39162a5b81375e7713d248591290f84fdbed32c86498b0e99dfd6c52a935c05

**Comment by falvaradorodriguez** [comment]
This isue is pending until this https://github.com/safe-global/safe-deployments/pull/672 is merged first.
