### ISSUE TITLE
[New chain]: Autonomys Testnet Nova Domain

### ISSUE THREAD

**Issue by DenSmolonski** [safe-global/safe-eth-py#1231]
### Summary

I would like to add Autonomys Testnet Nova Domain chain

### Chain ID

490000

### Chain detail URL

https://chainlist.org/chain/490000

### RPC URL

https://nova-0.gemini-3h.subspace.network/ws

### Blockscout Client URL

https://nova.subspace.network/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0xb57e4f74d954fa6e8353538e45e00a786e7095f724b98a95dcb023df4427c5eb

### Block explorer URL (Master copy)

https://nova.subspace.network/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Deployment Tx hash (Master copy L2)

0xcf692eadccae05803d1dda51b55de9773c8d19a29d6fe6d55278da81eb2ce646

### Block explorer URL (Master copy L2)

https://nova.subspace.network/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x73ea88a7ca7035f9482c7fb6c7c315baf640d36ff394881fabf2735157596e6c

### Block explorer URL (Proxy factory)

https://nova.subspace.network/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
Hi @DenSmolonski,

In this case, the right Blockscout client URL is https://nova.subspace.network/api/v1/graphql, please, update it in the issue description.

Thanks.

**Comment by falvaradorodriguez** [comment]
This issue is pending until this https://github.com/safe-global/safe-deployments/pull/704 is merged first.
