### ISSUE TITLE
[New chain]: Coston

### ISSUE THREAD

**Issue by jO-Osko** [safe-global/safe-eth-py#1249]
### Summary

I would like to add Coston chain (testnet for Songbird)

### Chain ID

16

### Chain detail URL

https://chainlist.org/chain/16

### RPC URL

https://coston-api.flare.network/ext/bc/C/rpc

### Blockscout Client URL

https://coston-explorer.flare.network/graphiql

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x21e6ab4075ea5f47bb0c7db3c74c14f272ec5f6c527476588092c5d9d1d7d3f0

### Block explorer URL (Master copy)

https://coston-explorer.flare.network/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0x3268cca44b84d882b547557e01ed8aa7d2af1904b67a7653d34b32afe50e7a3c

### Block explorer URL (Proxy factory)

https://coston-explorer.flare.network/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by falvaradorodriguez** [comment]
Hi @jO-Osko!
I have not been able to find version 1.4.1 on https://github.com/safe-global/safe-deployments/tree/main/src/assets/v1.4.1. Please, could you add it first?

**Comment by jO-Osko** [comment]
It has now been added: https://github.com/safe-global/safe-deployments/pull/732
