### ISSUE TITLE
[New chain]: IRISHub

### ISSUE THREAD

**Issue by mitch1024** [safe-global/safe-eth-py#1273]
### Summary

I would like to add IRISHub Mainnet which is the first mainnet in Cosmos Ecosystem: https://irisnet.org/

### Chain ID

6688

### Chain detail URL

https://chainlist.org/chain/6688

### RPC URL

https://evmrpc.irishub-1.irisnet.org

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0xde92d2a06a77ddfd447819c7b20182363576c53aab65b8d7dfb9afd1dd6a605b

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0xae25619dc9393b5d10c296467df1c4582ab3d6794fa07ea88cdc24c5bc36c3dc

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xdd2e5eb9770223822e8088ce49dd6ff8cbc0289241e8dba8035b26dc4eaf5113

**Comment by falvaradorodriguez** [comment]
Please, @mitch1024, add these addresses first in https://github.com/safe-global/safe-deployments.

Thanks!

**Comment by mitch1024** [comment]
> Please, @mitch1024, add these addresses first in https://github.com/safe-global/safe-deployments.
> 
> Thanks!

Done: https://github.com/safe-global/safe-deployments/pull/746
