### ISSUE TITLE
[New chain]: Cronos zkEVM Mainnet

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-eth-py#1288]
### Summary

- https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-388.json
- https://github.com/safe-global/safe-singleton-factory/issues/629
- https://github.com/safe-global/safe-deployments/pull/753

### Chain ID

388

### Chain detail URL

https://chainlist.org/chain/388

### RPC URL

https://mainnet.zkevm.cronos.org

### Version

1.3.0

### Address (Master copy)

0xB00ce5CCcdEf57e539ddcEd01DF43a13855d9910

### Deployment Tx hash (Master copy)

0xf4249bbc38606986159c839b4bb682ad7c1e000433e2f4031f3581679a7b3f29

### Address (Master copy L2)

0x1727c2c531cf966f902E5927b98490fDFb3b2b70

### Deployment Tx hash (Master copy L2)

0x2eabe6add88b36518aa9e3a0a9e520ba671bd841fe874130f746d0eac53057c7

### Address (Proxy factory)

0xDAec33641865E4651fB43181C6DB6f7232Ee91c2

### Deployment Tx hash (Proxy factory)

0x9636e889fc2b6f7e585a0e231eb9522b19f7b512fc424955691edb8f1f5d9722

**Comment by falvaradorodriguez** [comment]
Hello @ElvisKrop 

Indicate to me the block numbers as mentioned in the issue #1287.

Thanks

**Comment by ElvisKrop** [comment]
Master copy L1 - `6105`
Master copy L2 - `6104`
Proxy Factory - `6097`
