### ISSUE TITLE
[New chain]: Q Mainnet

### ISSUE THREAD

**Issue by KyrylR** [safe-global/safe-eth-py#1330]
### Summary

I would like to add the Q Mainnet network

### Chain ID

35441

### Chain detail URL

https://chainlist.org/chain/35441

### RPC URL

https://rpc.q.org

### Blockscout Client URL

https://explorer.q.org/api/v1/graphql

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0xafa5befd0ecff012da32c33a5511c4d7e47c380a1d15a49cdee32d9e012db63d

### Block explorer URL (Master copy)

https://explorer.q.org/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0xaa47e53eb87a62caf9093275684618fc3b94b7342a4759632db2dad0f2a18770

### Block explorer URL (Master copy L2)

https://explorer.q.org/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xbf39d10ec106bdd28cd00d058d86000dc7987b7dea495c53d9c7abd86eaa77a9

### Block explorer URL (Proxy factory)

https://explorer.q.org/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by KyrylR** [comment]
I am not sure what I did wrong with the Blockscout Client URL

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/5e938565-42c6-48c4-be01-5ce4f4907b4e">

As I was able to execute the request successfully

**Comment by KyrylR** [comment]
Sorry for spamming. I tried to fix the link to the explorer but failed

**Comment by falvaradorodriguez** [comment]
Hello @KyrylR 

I've been checking and the URL returns an error 403 when invoking from the script (even locally).

I have validated it manually and it is ok.

The PR is already merged.

Thank you.
