### ISSUE TITLE
[New chain]: Snaxchain 1.3.0 eip155

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-eth-py#1335]
### Summary

- https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-2192.json
- https://github.com/safe-global/safe-deployments/pull/787

> Unfortunately, the automated github check will fail since Snaxchain Mainnet is based on OP stack and Master Copies were predeployed.

### Chain ID

2192

### Chain detail URL

https://chainlist.org/chain/2192

### RPC URL

https://mainnet.snaxchain.io/

### Blockscout Client URL

https://explorer.snaxchain.io/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Block explorer URL (Master copy)

https://explorer.snaxchain.io/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Block explorer URL (Master copy L2)

https://explorer.snaxchain.io/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x145a5cbf4142848ca294cb93fce63026563846dd25fd00ff56a6682cdf1244a8

**Comment by ElvisKrop** [comment]
Unfortunately, the automated github check will fail since Snaxchain Mainnet is based on OP stack and Master Copies were predeployed.

**Comment by ElvisKrop** [comment]
Hello @falvaradorodriguez :wave: 
The contracts were predeployed, therefore I cannot give you a tx hash for master copies :disappointed:.
Shall I open a PR for this case?

**Comment by falvaradorodriguez** [comment]
> Hello @falvaradorodriguez 👋 The contracts were predeployed, therefore I cannot give you a tx hash for master copies 😞. Shall I open a PR for this case?

Hello @ElvisKrop 

No worries. In this particular case, you can leave the hash without value and we do the validation manually.

The automatic PR is already created and merged with the commit of the master copy addresses completed in block 0 (Genesis).

Thanks.

**Comment by ElvisKrop** [comment]
Thanks a lot @falvaradorodriguez !
Have a nice day :rocket:
