### ISSUE TITLE
[New chain]: Bahamut

### ISSUE THREAD

**Issue by fastexlabs** [safe-global/safe-eth-py#1347]
### Summary

I would like to add Bahamut chain.

### Chain ID

5165

### Chain detail URL

https://chainlist.org/chain/5165

### RPC URL

https://rpc1.bahamut.io

### Blockscout Client URL

https://api.ftnscan.com/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552

### Deployment Tx hash (Master copy)

0x8faaafda03b6aa1e53182993f0f8599cda760b8560d511a408bed3240b59e86a

### Block explorer URL (Master copy)

https://www.ftnscan.com/address/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552

### Address (Master copy L2)

0x3E5c63644E683549055b9Be8653de26E0B4CD36E

### Deployment Tx hash (Master copy L2)

0x8085b22f570fbcb0fa2399bf2af7ea802bb5dbb0a6b375ef30587c187d87c852

### Block explorer URL (Master copy L2)

https://www.ftnscan.com/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E

### Address (Proxy factory)

0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

### Deployment Tx hash (Proxy factory)

0x7d992e01cb5911b0f7d817364a911625e03ff70166d9a152452ec46dc7c732e8

### Block explorer URL (Proxy factory)

https://www.ftnscan.com/address/0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

**Comment by falvaradorodriguez** [comment]
Hey @fastexlabs 

First, it would be necessary to add the deployment [here](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments).

Thanks

**Comment by fastexlabs** [comment]
Hi @falvaradorodriguez 

Here is the link of the deployment that you asked for: https://github.com/safe-global/safe-deployments/issues/790
Can you please check and get back to me?

Thanks!

**Comment by falvaradorodriguez** [comment]
Hi @fastexlabs , 

I have seen that an issue has been created in the `safe-deployments` repository. The changes should be made in that repository before. You can take an existing PR in `safe-deployments` as an example and add it yourself. 

Once that step is done, we can add the addresses here. 

Thanks.

**Comment by fastexlabs** [comment]
Hi @falvaradorodriguez 

Here is the link of the Merged PR https://github.com/safe-global/safe-deployments/pull/818

Can you please check and get back to me?

Thanks!
