### ISSUE TITLE
[New chain]: OORT DevNet (Testnet)

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-eth-py#1363]
### Summary

I would like to add Safe v1.4.1 for OORT DevNet (Testnet)

### Chain ID

9700

### Chain detail URL

https://chainlist.org/chain/9700

### RPC URL

https://dev-rpc.oortech.com/

### Version

1.4.1

### Address (Master copy)

0x94ae01259d7e84D612070ca004D242F0d5213819

### Deployment Tx hash (Master copy)

0x5e76713eb17702bc836ff1bce58454835a0f33ca0870ce6c8a1d11d2830ae65c

### Block explorer URL (Master copy)

https://dev-scan.oortech.com/tx/0x5e76713eb17702bc836ff1bce58454835a0f33ca0870ce6c8a1d11d2830ae65c

### Address (Master copy L2)

0x24372682Db02aA5d5bA54168B49F3b54c1128154

### Deployment Tx hash (Master copy L2)

0x230f0de46efcefa107ce91890b2b5edf1de2b97859b287102c0a94215d020609

### Block explorer URL (Master copy L2)

https://dev-scan.oortech.com/tx/0x230f0de46efcefa107ce91890b2b5edf1de2b97859b287102c0a94215d020609

### Address (Proxy factory)

0x786Cf8CA0B88CD745aD2e3824Af7B17174dAe092

### Deployment Tx hash (Proxy factory)

0x1e9abcaf6110c647cd69586d8db8ad68f80dbc668623433c146ff630fdf8861d

### Block explorer URL (Proxy factory)

https://dev-scan.oortech.com/tx/0x1e9abcaf6110c647cd69586d8db8ad68f80dbc668623433c146ff630fdf8861d

**Comment by molecula451** [comment]
@falvaradorodriguez hey any thoughts on why it keeps getting back not valid 1.4.1? when in fact the contract returns 1.4.1 as VERSION()

**Comment by falvaradorodriguez** [comment]
Hi,

Are you sure that the compiled version of your contracts is [this](https://github.com/safe-global/safe-smart-account/tree/v1.4.1-build.0)?

It would be best if you used exactly the same commit.

**Comment by falvaradorodriguez** [comment]
Additionally, you need to add the addresses to this repository (https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments) first. 

Thanks

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
