### ISSUE TITLE
[New chain]: Vana Moksha Testnet

### ISSUE THREAD

**Issue by DenSmolonski** [safe-global/safe-eth-py#1365]
### Summary

I would like to add Vana Moksha Testnet. 

### Chain ID

14800

### Chain detail URL

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-14800.json

### RPC URL

https://rpc.moksha.vana.org/

### Blockscout Client URL

https://api.moksha.vanascan.io/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0xa7110f83206755f46b2d2b65b7e16414d8b136c51b43e9b1a322d7ef7d4a66d2

### Block explorer URL (Master copy)

https://moksha.vanascan.io/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Deployment Tx hash (Master copy L2)

0x43c33d5e8fdb3ad41ee203fbd27a7a2a5c3e9f748823bf634a66316033fe00a8

### Block explorer URL (Master copy L2)

https://moksha.vanascan.io/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0xdc3945f8e81785e4b25ca262f8bc62641570fd83b9ac3e29a75fff0458c39a3a

### Block explorer URL (Proxy factory)

https://moksha.vanascan.io/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
Pending of https://github.com/safe-global/safe-deployments/pull/814
