### ISSUE TITLE
[New chain]: Connext Sepolia

### ISSUE THREAD

**Issue by DenSmolonski** [safe-global/safe-eth-py#1366]
### Summary

I would like to add Connext Sepolia

### Chain ID

6398

### Chain detail URL

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-6398.json

### RPC URL

https://rpc.connext-sepolia.gelato.digital/

### Blockscout Client URL

https://scan.testnet.everclear.org/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0xa90d7bee95ec9195945de77c0dd59c9ddc4ab4a5d0affa2bb3f0380da3d3b68b

### Block explorer URL (Master copy)

https://scan.testnet.everclear.org/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Deployment Tx hash (Master copy L2)

0xfaf4966d61da32cea5ac9fa087255eaf19abf82d6d896b1a6a5d88237abfe874

### Block explorer URL (Master copy L2)

https://scan.testnet.everclear.org/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0xeaad43ff351467c35383b013916faeee19a6355c4bd17b525772364f88591dee

### Block explorer URL (Proxy factory)

https://scan.testnet.everclear.org/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
Pending merge of https://github.com/safe-global/safe-deployments/pull/815
