### ISSUE TITLE
[New chain]: Everclear Mainnet

### ISSUE THREAD

**Issue by DenSmolonski** [safe-global/safe-eth-py#1367]
### Summary

I would like to add Everclear Mainnet

### Chain ID

25327

### Chain detail URL

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-25327.json

### RPC URL

https://rpc.everclear.raas.gelato.cloud

### Blockscout Client URL

https://scan.everclear.org/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0x53f0d1ebc9ee6a3e0579a712fa1d317c7547dcc4c9205f131998230efe480480

### Block explorer URL (Master copy)

https://scan.everclear.org/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Deployment Tx hash (Master copy L2)

0x838248c16d1d9d68df1382518c6ab8a23f779f86d2460163c37b6a668a121f58

### Block explorer URL (Master copy L2)

https://scan.everclear.org/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x001887f62d87126e4546f5d365297394986be0229fa14d3a4de93c7f29fd31d7

### Block explorer URL (Proxy factory)

https://scan.everclear.org/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
Pending merge of https://github.com/safe-global/safe-deployments/pull/816
