### ISSUE TITLE
[New chain]: Game 7 Testnet 1.4.1

### ISSUE THREAD

**Issue by msvstj** [safe-global/safe-eth-py#1396]
### Summary

I would like to add Game7 Testnet 1.4.1 contract and block explorer data

### Chain ID

13746

### Chain detail URL

https://chainlist.org/chain/13746

### RPC URL

https://testnet-rpc.game7.io

### Blockscout Client URL

https://testnet.game7.io/api/v1/graphql

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0xbb88598d764ae93896d582098734e7991c02f24f49bd013938d43ab62a607996

### Block explorer URL (Master copy)

https://testnet.game7.io/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0x6a7bb46f2f96c0b06835c532e6143e48268ddf4cbc6e5e7773c924cf69e28b02

### Block explorer URL (Master copy L2)

https://testnet.game7.io/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xe1741bd66a605cb0919e084f131c677aaf2f9441b4ae9f1f7bef290c2b9b14b5

### Block explorer URL (Proxy factory)

https://testnet.game7.io/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
