### ISSUE TITLE
[New chain]: Game 7 Mainnet 1.4.1

### ISSUE THREAD

**Issue by msvstj** [safe-global/safe-eth-py#1397]
### Summary

I would like to add Game7 Mainnet 1.4.1 contract and block explorer data

### Chain ID

2187

### Chain detail URL

https://chainlist.org/chain/2187

### RPC URL

https://mainnet-rpc.game7.io

### Blockscout Client URL

https://mainnet.game7.io/api/v1/graphql

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x06e07921768a973637277bcd1640fd423973e58f3a6fb9d38743931074a94f26

### Block explorer URL (Master copy)

https://mainnet.game7.io/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0x802aea4b918300aaa9c7fa4598ae89834dd9e5245e3e041e228e7769d2dbecf9

### Block explorer URL (Master copy L2)

https://mainnet.game7.io/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xa2985f80a1d62b2878312ef100b276f24ecf61ff2c43b1809e90750a565bf20d

### Block explorer URL (Proxy factory)

https://mainnet.game7.io/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by msvstj** [comment]
Edited the mixed block explorer / tx hash values

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by falvaradorodriguez** [comment]
Hi @msvstj 
Please, Could you add the deployment in the [safe-deployments-repo](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments) first? Thanks

**Comment by msvstj** [comment]
Yes, 
Sorry @falvaradorodriguez, missed that on my part, done: https://github.com/safe-global/safe-deployments/pull/843
