### ISSUE TITLE
[New chain]: 1.3.0 contracts for new Cronos zkEVM Testnet based on zkSync

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-eth-py#1406]
### Summary

- https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-240.json
- https://github.com/safe-global/safe-singleton-factory/issues/751
- https://github.com/safe-global/safe-deployments/pull/849

### Chain ID

240

### Chain detail URL

https://chainlist.org/chain/240

### RPC URL

https://testnet.zkevm.cronos.org

### Version

1.3.0

### Address (Master copy)

0xB00ce5CCcdEf57e539ddcEd01DF43a13855d9910

### Deployment Tx hash (Master copy)

0x11e9002c8489985d8a41eab6898bb115c20815708ff010d495ce54f73259e4c6

### Address (Master copy L2)

0x1727c2c531cf966f902E5927b98490fDFb3b2b70

### Deployment Tx hash (Master copy L2)

0xe429b87ff0223fac9a4068600ed2cfc7daa9ae2c6e83526cb8c1eebfee9d6502

### Address (Proxy factory)

0xDAec33641865E4651fB43181C6DB6f7232Ee91c2

### Deployment Tx hash (Proxy factory)

0xbf90209ccc2ec9a40c9436d2b8967b9e9196a36ca19c3a7e2ba63279949b03ec

**Comment by falvaradorodriguez** [comment]
Validated manually with the [explorer](https://explorer.zkevm.cronos.org/testnet/tx/0xbf90209ccc2ec9a40c9436d2b8967b9e9196a36ca19c3a7e2ba63279949b03ec) ✅
