### ISSUE TITLE
[New chain]: OORT Testnet

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-eth-py#1412]
### Summary

Would like to add 1.4.1 to OORT Testnet

### Chain ID

9700

### Chain detail URL

https://chainlist.org/chain/9700

### RPC URL

https://dev-rpc.oortech.com

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0xf5247a63a6acc854163d4aff4315c37a1f9c39374a029e31850e4d4593cda30c

### Block explorer URL (Master copy)

https://dev-scan.oortech.com/tx/0xf5247a63a6acc854163d4aff4315c37a1f9c39374a029e31850e4d4593cda30c

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0x9f1d349a0790707e17e9ad528919617438187ec09e19b45ac21f6ed805b09caf

### Block explorer URL (Master copy L2)

https://dev-scan.oortech.com/tx/0x9f1d349a0790707e17e9ad528919617438187ec09e19b45ac21f6ed805b09caf

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xf9aff0c5225c1133319b68eb45d28e4ce3ebb09eaeca17357b450e2d86a03fb5

### Block explorer URL (Proxy factory)

https://dev-scan.oortech.com/tx/0xf9aff0c5225c1133319b68eb45d28e4ce3ebb09eaeca17357b450e2d86a03fb5

**Comment by falvaradorodriguez** [comment]
Hi @molecula451,

Please first add the addresses of the deployments in the [deployments repository](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments). 

Thanks.

**Comment by molecula451** [comment]
added, thanks
