### ISSUE TITLE
[New chain]: Ink Sepolia

### ISSUE THREAD

**Issue by leonimella** [safe-global/safe-eth-py#1420]
### Summary

I would like to add Ink Sepolia chain contracts addresses

### Chain ID

763373

### Chain detail URL

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-763373.json

### RPC URL

https://rpc-gel-sepolia.inkonchain.com

### Blockscout Client URL

https://explorer-sepolia.inkonchain.com/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Block explorer URL (Master copy)

https://explorer-sepolia.inkonchain.com/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Block explorer URL (Master copy L2)

https://explorer-sepolia.inkonchain.com/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0xf951597af867ad3afd83c876625a1706d596213d5a1ffe4a3b0d610d283e2cb4

### Block explorer URL (Proxy factory)

https://explorer-sepolia.inkonchain.com/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
- Pending to merge: https://github.com/safe-global/safe-deployments/pull/861
