### ISSUE TITLE
[New chain]: Nahmii 3 Mainnet 1.4.1

### ISSUE THREAD

**Issue by gr4yha7** [safe-global/safe-eth-py#1427]
### Summary

https://github.com/safe-global/safe-singleton-factory/issues/761

### Chain ID

4061

### Chain detail URL

https://chainlist.org/chain/4061

### RPC URL

https://rpc.n3.nahmii.io

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x62cd6609d8e431c8467b219a288fb8bb51c888f4e63756bed4dea8f6174214a8

### Block explorer URL (Master copy)

https://explorer.nahmii.io/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0x5b54519f0e653eb7c6c8dbddf64be735073f849906555278548fe678324d34c8

### Block explorer URL (Master copy L2)

https://explorer.nahmii.io/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xe09829363f0280d98949f819136bdce3077e994f2fb89006757f6cb53d5c3a1b

### Block explorer URL (Proxy factory)

https://explorer.nahmii.io/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by falvaradorodriguez** [comment]
- Pending to merge https://github.com/safe-global/safe-deployments/pull/869

**Comment by gr4yha7** [comment]
> * Pending to merge [feat: add Nahmii 3 mainnet(4061) safe-deployments#869](https://github.com/safe-global/safe-deployments/pull/869)

@falvaradorodriguez PR now merged.
