### ISSUE TITLE
[New chain]: HashKey Testnet 1.3.0

### ISSUE THREAD

**Issue by HashKeyCloud** [safe-global/safe-eth-py#1449]
### Summary

I would like to add HashKey Testnet 1.3.0 chain addresses

### Chain ID

133

### Chain detail URL

https://chainlist.org/chain/133

### RPC URL

https://hashkeychain-testnet.alt.technology

### Blockscout Client URL

https://hashkeychain-testnet-explorer.alt.technology/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552

### Deployment Tx hash (Master copy)

0x909b657525c631b9179c9f2689d017a8d4aff7330becf1217d0f88e8a0171085

### Block explorer URL (Master copy)

https://hashkeychain-testnet-explorer.alt.technology/address/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552

### Address (Master copy L2)

0x3E5c63644E683549055b9Be8653de26E0B4CD36E

### Deployment Tx hash (Master copy L2)

0x1f9208fa7e9acc7ed4af97fe2eda5acf8fe6d4543e6b41daad1e02fff536ef2c

### Block explorer URL (Master copy L2)

https://hashkeychain-testnet-explorer.alt.technology/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E

### Address (Proxy factory)

0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

### Deployment Tx hash (Proxy factory)

0xa5c4d85c5b5d39f5968ad7730170acbcce9a64c4a241fb2c30857ee8934b33a7

### Block explorer URL (Proxy factory)

https://hashkeychain-testnet-explorer.alt.technology/address/0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

**Comment by falvaradorodriguez** [comment]
Hi @HashKeyCloud,

Please, Could you add the deployment in the [safe-deployments-repo](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments) first? Thanks

It's necessary to have the chain addresses in the deployments repository before executing this issue.

**Comment by HashKeyCloud** [comment]
> Hi @HashKeyCloud,
> 
> Please, Could you add the deployment in the [safe-deployments-repo](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments) first? Thanks
> 
> It's necessary to have the chain addresses in the deployments repository before executing this issue.

done.
https://github.com/safe-global/safe-deployments/pull/893
