### ISSUE TITLE
[New chain]: HashKey Testnet 1.4.1

### ISSUE THREAD

**Issue by HashKeyCloud** [safe-global/safe-eth-py#1450]
### Summary

I would like to add HashKey Testnet 1.4.1 chain addresses

### Chain ID

133

### Chain detail URL

https://chainlist.org/chain/133

### RPC URL

https://hashkeychain-testnet.alt.technology

### Blockscout Client URL

https://hashkeychain-testnet-explorer.alt.technology/api/v1/graphql

### Version

1.4.1

### Address (Master copy)

0x41675C099F32341bf84BFc5382aF534df5C7461a

### Deployment Tx hash (Master copy)

0x7c2fb95f3286c83814b04ee35ca3913bfc49d77e9c9daaa0554a5e886f4315e1

### Block explorer URL (Master copy)

https://hashkeychain-testnet-explorer.alt.technology/address/0x41675C099F32341bf84BFc5382aF534df5C7461a

### Address (Master copy L2)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy L2)

0x5028e9fbf1373532679f70442d7926e48314b1ba2e1498d2b23622201d9ae2b0

### Block explorer URL (Master copy L2)

https://hashkeychain-testnet-explorer.alt.technology/address/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0x13c3dd69d925ccabe3acbb13282de54289aa6d9cf09c642e68738a3d29110f1a

### Block explorer URL (Proxy factory)

https://hashkeychain-testnet-explorer.alt.technology/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by falvaradorodriguez** [comment]
Hi @HashKeyCloud,

Please, Could you add the deployment in the [safe-deployments-repo](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#adding-additional-deployments) first? Thanks

It's necessary to have the chain addresses in the deployments repository before executing this issue.

**Comment by falvaradorodriguez** [comment]
- Pending to merge https://github.com/safe-global/safe-deployments/pull/898

**Comment by HashKeyCloud** [comment]
> * Pending to merge [feat: add 1.4.1 canonical contracts for HashKey Chain Testnet safe-deployments#898](https://github.com/safe-global/safe-deployments/pull/898)

done.
