### ISSUE TITLE
SafeTx excute: Fail with error 'GS001'

### ISSUE THREAD

**Issue by zaneran9** [safe-global/safe-eth-py#273]
**Describe the bug**
I built the SafeTx object locally, multi-signed and executed, but I have a problem with the tx. the tx hash is [here](https://rinkeby.etherscan.io/tx/0xe0b017d2e2ffb31ba81e79342422ef7dee90bb2daeb8ca9e1f6e9645e503a8f6).

**To Reproduce**
execute function "send_multiSig_transaction"

**Expected behavior**
The query result is a successful hash.

**Additional context**
python==3.8.5
safe-eth-py==4.1.0

code: 

```python

from eth_typing import URI
from gnosis.eth import EthereumClient
from gnosis.safe.safe_tx import SafeTx

def send_multiSig_transaction():
    eth_client = EthereumClient(ethereum_node_url=URI('https://rinkeby.infura.io/v3/60b1533909b84f0e8ac61adbf44f2e38'))
    safe_tx = SafeTx(
        ethereum_client=eth_client,
        safe_address='0xC6bB445360B5122F4ED52F5CF206ff6388201573',
        to='0xf385FFD916ab0fB2DAd83e613d20970515f4844B',
        value=0,  
 data=b'0xa9059cbb0000000000000000000000001ab96c8568c5226efcb95ac5e5437f3ec48ade620000000000000000000000000000000000000000000000000000000000000001',
        operation=0,
        safe_tx_gas=200000,
        base_gas=21000,
        gas_price=1200000000,
        gas_token='0x0000000000000000000000000000000000000000',
        refund_receiver='0x0000000000000000000000000000000000000000',
        # signatures=b'',
        # safe_nonce=0,
        # safe_version='',
        # chain_id=4

    )
    # owner1
    safe_tx.sign('owner1 secret')
    # owner2
    safe_tx.sign('owner2 secret')
    data = safe_tx.execute(tx_sender_private_key='owner2 secret',
                           tx_gas_price=2000000000, tx_gas=200000)
    return data
```

**Comment by Uxio0** [comment]
According to https://github.com/safe-global/safe-contracts/blob/da66b45ec87d2fb6da7dfd837b29eacdb9a604c5/docs/error_codes.md , threshold needs to be defined, so the Safe is not correctly set up.

I have just checked and indeed Safe has no owners, no threshold...

**Comment by zaneran9** [comment]
> According to https://github.com/safe-global/safe-contracts/blob/da66b45ec87d2fb6da7dfd837b29eacdb9a604c5/docs/error_codes.md , threshold needs to be defined, so the Safe is not correctly set up.
> 
> I have just checked and indeed Safe has no owners, no threshold...

Thanks for your reply quickly.

**Comment by zaneran9** [comment]
Hi, Uxio0, I'm sure the current safe `0xd806f3169620cca5a3a5778d03a0984acc76c740`  is normal. But after I initiate the transaction with above codes, it tells me GS010 in the transaction log of the block explorer.the hash is `0xb945a08d6037be7c195729e785107fcdba93c080368a6a593771917610fadece`.  I tried to increase safe_tx_gas and base_gas and it didn't work, what's the problem? SafeTx's  data or signatures error? Thanks.

**Comment by Uxio0** [comment]
> 

Leave `safe_tx_gas=0` and `base_gas=0`. They are not needed in contracts `v1.3.0`

**Comment by zaneran9** [comment]
> @zaneran9 Leave `safe_tx_gas=0` and `base_gas=0`. They are not needed in contracts `v1.3.0`

@Uxio0  According to your prompt, It tells me `GS013`. then I set `gas_price=1500000000` , `safe_tx_gas=0` and `base_gas=0`, the transaction is not completely successful, the transaction status is successful (tx hash is `0xe53669e583be3fbcbdc0740a36af0aca01ad5e4b9bd8ca560493c00012750ded`), but the erc20-token has not been transferred. Please tell me if the other parameters of SafeTx are correct? Especially  `data`  or `signatures` section. Thanks again!

**Comment by Uxio0** [comment]
> @Uxio0 According to your prompt, It tells me `GS013`. then I set `gas_price=1500000000` , `safe_tx_gas=0` and `base_gas=0`, the transaction is not completely successful, the transaction status is successful (tx hash is `0xe53669e583be3fbcbdc0740a36af0aca01ad5e4b9bd8ca560493c00012750ded`), but the erc20-token has not been transferred. Please tell me if the other parameters of SafeTx are correct? Especially `data` or `signatures` section. Thanks again!

Let also `gas_price=0`. I still see that tx is good but transaction goes out of gas. Are you setting gas manually? (As I see 200,000 as it's a very exact number).

And please, this is only for issues on the library, for developer issues you should go to https://ethereum.stackexchange.com/questions/tagged/gnosis-safe 😉
