### ISSUE TITLE
Introduce method `SafeTx.api_post_data`

### ISSUE THREAD

**Issue by bh2smith** [safe-global/safe-eth-py#284]
Currently, in order to post Safe transactions to the web interface (with this project as a dependency), we have to manually construct the `post_data` dictionary out of all the fields already contained in `safe_tx`. Since a `SafeTx` already contains the relevant info to build the post_data, it would be nice if there were some exposed method that would return the required format.

For example, the content of this method (taken from `safe-cli`) which constructs the post data would be nice to include here in this project:

https://github.com/5afe/safe-cli/blob/7a70a18c36b163ee91d5c763208ba1b1c9571317/safe_cli/api/transaction_service_api.py#L198-L222

**Comment by Uxio0** [comment]
@bh2smith What do you think about https://github.com/safe-global/safe-eth-py/pull/292 ?

**Comment by bh2smith** [comment]
Hey @Uxio0 - Overall I think it looks great. One additional thing I noticed is that `ethereum_client` is often expected to be passed along with these classes, but its really only needed for somethings that people may not necessarily want (in this case, it looks like its used for gas estimation). I wonder if we could (maybe at another point in time), make the existence of a valid `EthereumClient` optional for situations where its unnecessary.

**Comment by bh2smith** [comment]
Accidentally closed. sorry.

**Comment by Uxio0** [comment]
> Hey @Uxio0 - Overall I think it looks great. One additional thing I noticed is that `ethereum_client` is often expected to be passed along with these classes, but its really only needed for somethings that people may not necessarily want (in this case, it looks like its used for gas estimation). I wonder if we could (maybe at another point in time), make the existence of a valid `EthereumClient` optional for situations where its unnecessary.

Makes sense

**Comment by Uxio0** [comment]
I did the change on PR to make `ethereum_client` optional
