### ISSUE TITLE
Add Gnosis>=0.1.1 dependency to install_requires

### ISSUE THREAD

**Issue by bh2smith** [safe-global/safe-eth-py#285]
My IDE is forcing me to install what is assumed to be a based dependency of this package:

<img width="619" alt="Screenshot 2022-07-04 at 11 54 30 AM" src="https://user-images.githubusercontent.com/11778116/177130821-cecd7d92-73d3-44e8-8094-f0d63e1e3cdc.png">

Could be resolved by adding
```
Gnosis>=0.1.1
```
to the `setup.py` file here:

https://github.com/safe-global/safe-eth-py/blob/791ca1ecfb3337825266d41d5f4534d7c0fe0fc0/setup.py#L11-L22

**Comment by Uxio0** [comment]
Hi @bh2smith, this is an issue of Pycharm and not from us. `gnosis` package is not related to us anyway, I would not recommend to add packages we don't know about just because the IDE thinks it should be it 😉 

More info: https://youtrack.jetbrains.com/issue/PY-24177
