### ISSUE TITLE
Deprecation Warning: signHash

### ISSUE THREAD

**Issue by bh2smith** [safe-global/safe-eth-py#294]
https://github.com/safe-global/safe-eth-py/blob/3f01e6fa1bd8b45e9dd42b9fc14cf38ea454ad33/gnosis/safe/safe_tx.py#L421

When using this package, I got a warning:

```
DeprecationWarning: signHash is deprecated in favor of sign_message
```

coming from a dependency: eth_account/account.py:584:

I looked a bit into what it would take to make the transition here, but one cannot simply interchange the use of `account.signHash` with `account.sign_message`, we would need to actually provide also a `SignableMessage` with attributes:

```
    version: bytes  # must be length 1
    header: bytes  # aka "version specific data"
    body: bytes  # aka "data to sign"
```

Not sure exactly what to put here just yet. but its all contained here in [eth_account.messages.py](https://github.com/ethereum/eth-account/blob/master/eth_account/messages.py
)

**Comment by Uxio0** [comment]
Hi @bh2smith , we are aware and this is not on us. More info: https://github.com/ethereum/eth-account/issues/85

**Comment by bh2smith** [comment]
Did you manage to find a way to suppress the warning?

**Comment by Uxio0** [comment]
> Did you manage to find a way to suppress the warning?

No, that's why it's still there
