### ISSUE TITLE
Add/update oracles to retrieve the price

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#343]
# What is needed?
Currently `safe-eth-py` have several oracles implemented to retrieve the price from them but the last update of them was on October of 2021.  
I would like to review the oracles implemented to check if new versions of contracts are deployed eg: UniSwapV3, and research if we can add some more new oracles. 

# Background
The focus of this issue is add more opportunities to retrieve the price from decentralized options before centralized options. 

# Related issues
No issues related.

**Comment by Uxio0** [comment]
Related to #342

**Comment by Uxio0** [comment]
Sure
