### ISSUE TITLE
Estimation tx gas lower than required 

### ISSUE THREAD

**Issue by JacqueGM** [safe-global/safe-eth-py#410]
The value of the estimation for some transaction (gnosis chain) is lower than the value required, so we think it's becuase the offset is a bit low. We tried locally to change it from its current value to 23000, and we get the value required in each transaction
Now the result we get is around 89220 but the value required for the transaction is 91064 (which we achieve if we increase the WEB3_ESTIMATION_OFFSET) - 

https://github.com/safe-global/safe-eth-py/blob/d7aa4787a5c562b0487fe5304706e10b359874ed/gnosis/safe/safe.py#L793

Error that we see in our logs :
`InvalidGasEstimation: Gas should be at least equal to safe-tx-gas=91064 and base-gas=48528. Current is safe-tx-gas=89950 and base-gas=48528
`

**Comment by Uxio0** [comment]
Fixed on https://github.com/safe-global/safe-eth-py/pull/411
