### ISSUE TITLE
Refactor retrieve_version and add cached property 

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#433]
# What is needed?
Currently retrieve_version method do a call to the RPC to return the version of the safe contract. 
An improvement performance of that could be convert this function in a property method of safe or contract and enable in that the cached_property.
The idea is, having an instance of a Safe, get the version like `safe.version` or `safe.contract.version` . 

# Background
This approach was discussed here https://github.com/safe-global/safe-eth-py/pull/422#discussion_r1067228040

**Comment by Uxio0** [comment]
The only thing pulling me out from caching version is that it can change and break existing services. If Safe gets updated we don't have an easy way to detect that. Also I would argue that if we do this for `version` we should do the same for other attributes like `owners` and `threshold`

**Comment by Uxio0** [comment]
I will close this and maybe we can analyze that again if we want to refactor the Safe methods
