### ISSUE TITLE
Remove deprecated pysha3 from dependencies - can't install in python 3.11

### ISSUE THREAD

**Issue by rollue** [safe-global/safe-eth-py#441]
https://github.com/tiran/pysha3

pysha3 is no longer maintained and it can't be installed in python 3.11

**Comment by Uxio0** [comment]
Thanks, we are aware (we maintain a fork for pysha3) and it's addressed here https://github.com/safe-global/safe-eth-py/pull/416

**Comment by rollue** [comment]
thanks didn't see this :)
