### ISSUE TITLE
Add Syscoin Addresses (Tanenbaum, Mainnet & ROLLUX)

### ISSUE THREAD

**Issue by GundamDweeb** [safe-global/safe-eth-py#487]
# What is needed?
Adding in the Syscoin Safe Deployment addresses after deployment has been done.

Relies on :

https://github.com/safe-global/safe-singleton-factory/issues/123
https://github.com/safe-global/safe-singleton-factory/issues/124
https://github.com/safe-global/safe-singleton-factory/issues/125

# Background
After deployment has been made, the addresses need to be added here first before changes to safe transaction service can be made.

# Related issues

https://github.com/safe-global/safe-singleton-factory/issues/123
https://github.com/safe-global/safe-singleton-factory/issues/124
https://github.com/safe-global/safe-singleton-factory/issues/125

ATT:  @develcuy

**Comment by develCuy** [comment]
@Uxio0, we'll have @GundamDweeb do the PR once we have your PR for: https://github.com/safe-global/safe-singleton-factory/issues/123 https://github.com/safe-global/safe-singleton-factory/issues/124 and https://github.com/safe-global/safe-singleton-factory/issues/125

**Comment by fernando-syslabs** [comment]
@GundamDweeb, please add https://github.com/safe-global/safe-singleton-factory/issues/153 (Rollux Mainnet) to the description of this task. Thanks in advance!

**Comment by Uxio0** [comment]
Closing this due inactivity
