### ISSUE TITLE
EtherscanClient vs BlockscoutClient format?

### ISSUE THREAD

**Issue by comverser** [safe-global/safe-eth-py#490]
Can you please answer the following questions?

1. What are the purposes of `NETWORK_WITH_URL` and `NETWORK_WITH_API_URL` in the [EtherscanClient](https://github.com/safe-global/safe-eth-py/blob/174053920e0717cc9924405e524012c5f953cd8f/gnosis/eth/clients/etherscan_client.py#L24) class? Are they required and important? Can I add a custom explorer URL to the list that is not based on Etherscan, which is not an opensource? (i.e. If the format of the custom explorer API does not match that of [Etherscan’s API](https://docs.etherscan.io/api-endpoints/accounts), can I still add it to the list without problem?)

2. What is the purpose of the [BlockscoutClient](https://github.com/safe-global/safe-eth-py/blob/174053920e0717cc9924405e524012c5f953cd8f/gnosis/eth/clients/blockscout_client.py#L20) class? Is it similar to the EtherscanClient class? What happens if someone omits writing either the EtherscanClient or BlockscoutClient classes?

3. Do the URLs mentioned relate to or depend on infrastructure [code](https://github.com/safe-global/safe-infrastructure/blob/main/docs/chain_info.md#block-explorer-url-templates)?

**Comment by Uxio0** [comment]
1. `NETWORK_WITH_URL` is meant for providing links to etherscan client, `NETWORK_WITH_API_URL` is meant to access the API. Some etherscan deployments for some side chains have a different API url. No, you cannot add not etherscan compatible block explorer (unless API is totally compatible with etherscan).
2. Yes, it has the same objective but using BlockScout API. If you omit both classes services using `safe-eth-py` (like `safe-transaction-service`) will not be able to do some things like retrieving ABIs for contracts.
3. No, that's related to the `safe-config-service` configuration.
