### ISSUE TITLE
EtherscanClient and safe-global/safe-infrastructure

### ISSUE THREAD

**Issue by comverser** [safe-global/safe-eth-py#494]
My goal is to run the [safe-infrastructure](https://github.com/safe-global/safe-infrastructure) service on a custom chain by following the [Guide to run our services locally](https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md).

Based on [this post](https://github.com/safe-global/safe-deployments/issues/211#issuecomment-1485365021), I discovered that the PR should be submitted to this repository.

If neither the EtherscanClient nor the BlockscoutClient is added for the custom chain (e.g. [Add Evmos Mainnet & Testnet](https://github.com/safe-global/safe-eth-py/pull/493)) because its block explorer doesn’t support the format of either the Etherscan API or the Blockscout API, could this cause problems for running the Multi-sig app (i.e. safe-infrastructure)?

**Comment by Uxio0** [comment]
You will loose ABI decoding support, as we use blockscout/etherscan as the source. We also use Sourcify, so if your network is supported you should be alright
