### ISSUE TITLE
Claim Network for Ronin Networks

### ISSUE THREAD

**Issue by huyngopt1994** [safe-global/safe-eth-py#584]
Hi team, Right now our ronin network is running in the below chains
1. Mainnet: 2020 
2. Testnet: 2021
Right now, I see those chains already are reserved by some chains which are not activated anymore. And our team is customizing the source code for making it works. Hence, Could I create a PR in this repo for updating those chain names again? 
@Uxio0  Please take a look

**Comment by Uxio0** [comment]
Hi, we will honor https://chainlist.org/ information, anything that is accepted there will be accepted as a PR in this repo

**Comment by huyngopt1994** [comment]
oke let me work with their team for updating from their side firstly.

**Comment by Uxio0** [comment]
Closing this due inactivity
