### ISSUE TITLE
Generate addresses from safe-deployments.py

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#693]
# What is needed?
`addresses.py` include the addresses of Safe singleton contracts (L1, L2, ProxyFactory) and the block number when the contract was deployed to start the indexing process from that block. 
Search the block for every address is a cumbersome task, I would like to include a generator to get the block from blockexplorer (etherscan and blockscout) automatically for the new addresses added on safe-deployments.

**Comment by Uxio0** [comment]
We don't see this feasible for new networks, as most lack blockexplorer or they use a non standard API
