### ISSUE TITLE
Remove delegate API client shouldn't sign the message

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#750]
# What is needed?
The function [remove_delegate](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/safe/api/transaction_service_api.py#L240) of transaction service api is signing the message with wallet provided by parameter, but this signature should happens outside of the `remove_delegate` function to let other types of wallets as hardware wallets sign the message.
I'd suggest that `remove_delegate` should just receive the message_hash and the signature.

**Comment by Uxio0** [comment]
Makes total sense @moisses89 , good call
