### ISSUE TITLE
Define a process for merging address PRs

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-eth-py#810]
We spend a lot of thing reviewing and merging PRs adding addresses for Safe Contracts in new networks.

We need to define a process to make the process smother.

**Comment by bertux** [comment]
Thanks because even when the PR is reviewed and merged, then it needs also to be released so it can be used in safe-infrastructure repository.
I've seen there is a publish part in the GitHub Action but it's skipped so I don't know yet when the merged PR will be usable in the python package. Should I publish my own version while waiting for official publish ?

**Comment by falvaradorodriguez** [comment]
As a result of this task, we have defined the following process:

In the repository `https://github.com/safe-global/safe-eth-py` 

Create an issue with the GitHub issue form syntax that has the following fields:

- Summary
- Chain ID (required)
- Chain detail URL (chainlist.org) (required)
- RPC Server Address (required)
- Blockscout Client URL
- Etherscan Client URL
- Contract version (required)
- Address (Master copy)
- Deployment block (Master copy)
- Block explorer URL (Master copy)
- Address (Proxy factory)
- Deployment block (Proxy factory)
- Block explorer URL (Proxy factory)


Create a GitHUb action that will be executed when the `/executed` command is commented in the issue. The GitHUb action will execute the following actions:

- Validate that the person executing the command has owner permissions on the repository
    - In affirmative case:
        - Notify the start of execution with a comment in the issue
    - In negative case:
        - Notify that the person does not have permissions with a comment in the issue

- Obtain the necessary entries from the issue body

- Execute a script to do the necessary modifies and create the automatic PR.

- Notify the end of execution with a comment in the issue.

As indicated above, the next task has been created.

- https://github.com/safe-global/safe-eth-py/issues/826

**Comment by moisses89** [comment]
> Thanks because even when the PR is reviewed and merged, then it needs also to be released so it can be used in safe-infrastructure repository.
> I've seen there is a publish part in the GitHub Action but it's skipped so I don't know yet when the merged PR will be usable in the python package. Should I publish my own version while waiting for official publish ?

We are releasing more or less 2 per month, if you need urgently the main version when your PR is merged you can modify your requirements as follow to use main branch:
`safe-eth-py @ git+https://github.com/safe-global/safe-eth-py@main` or if need `django` support
 `safe-eth-py[django] @ git+https://github.com/safe-global/safe-eth-py@main`

**Comment by bertux** [comment]
Thanks, I've seen it has been released last week, but it's more global feedback about Safe dependencies needed by safe-infrastructure to add a new chain.
So I should put this feedback in other repository.
