### ISSUE TITLE
[New chain]: IotaEVM

### ISSUE THREAD

**Issue by Vaphen** [safe-global/safe-eth-py#867]
### Summary

Add new chain IotaEVM

### Chain ID

8822

### Chain detail URL

https://chainlist.org/chain/8822

### RPC URL

https://json-rpc.evm.iotaledger.net

### Blockscout Client URL

https://iota-evm.blockscout.com/graphiql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0xe3e081b942f7c83a29c329d95ac93531a10861eb582343aefaf53db2392b3ccd

### Block explorer URL (Master copy)

https://iota-evm.blockscout.com/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x0c1279068b9a46e946e9b9d39a8973490ad7c49af3bb506e83132687d124402c

### Block explorer URL (Proxy factory)

https://iota-evm.blockscout.com/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
@Vaphen The blockscout client url is not correct, please update the issue with the correct  `https://iota-evm.blockscout.com/graphiql`. Thanks

**Comment by Vaphen** [comment]
@falvaradorodriguez Done!
