### ISSUE TITLE
[New chain]: ShimmerEVM

### ISSUE THREAD

**Issue by Vaphen** [safe-global/safe-eth-py#868]
### Summary

Add support for ShimmerEVM§

### Chain ID

148

### Chain detail URL

https://chainlist.org/chain/148

### RPC URL

https://json-rpc.evm.shimmer.network

### Blockscout Client URL

https://explorer.evm.shimmer.network/

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0x2bb73d54fe4a2cc912fa979c828f2a7cfbca0e06dc7b6099f843fd0676748cb2

### Block explorer URL (Master copy)

https://explorer.evm.shimmer.network/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0xd3c55b2748e813b04e0415ccde72e145b965cff87343bc189d9b7de75bcafe6c

### Block explorer URL (Proxy factory)

https://explorer.evm.shimmer.network/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

**Comment by falvaradorodriguez** [comment]
@Vaphen The blockscout client URL was not correct. I have updated it in the automatic PR: `https://explorer.evm.shimmer.network/graphiql`.
