### ISSUE TITLE
[New chain]: Bitlayer Testnet

### ISSUE THREAD

**Issue by Zerppen** [safe-global/safe-eth-py#882]
### Summary

Add support for Bitlayer Testnet

### Chain ID

200810

### Chain detail URL

https://chainlist.org/chain/200810

### RPC URL

https://testnet-rpc.bitlayer.org

### Etherscan Client URL

https://testnet-scan.bitlayer.org/en-us

### Version

1.3.0+L2

### Address (Master copy)

0x3E5c63644E683549055b9Be8653de26E0B4CD36E

### Deployment Tx hash (Master copy)

0xa092ecab846eb01ab73c8b9aa5778e394cc376300177d156928d8ba7323ed1f6

### Block explorer URL (Master copy)

https://testnet-scan.bitlayer.org/en-us/tx/0xa092ecab846eb01ab73c8b9aa5778e394cc376300177d156928d8ba7323ed

### Address (Proxy factory)

0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

### Deployment Tx hash (Proxy factory)

0x6f8410d95551f1bd5fa0225fd0d3b6b40c20b61ee4c6a60ebd6e119868ea3277

### Block explorer URL (Proxy factory)

https://testnet-scan.bitlayer.org/en-us/address/0xa6b71e26c5e0845f74c812102ca7114b6a896ab2

**Comment by falvaradorodriguez** [comment]
@Zerppen Can you check the URL of Etherscan? It is not a required field, if it does not exist, you can skip it. Thanks

**Comment by falvaradorodriguez** [comment]
Hello @Zerppen 

We close the issue due to inactivity. If you still need to add the addresses, please re-open a new issue taking into account the above comment.

Thanks
