### ISSUE TITLE
Refactor etherscan client

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-eth-py#887]
# What is needed?
Currently etherscan client require to configure two identicatl URLS. 
https://github.com/safe-global/safe-eth-py/blob/324a5d0e7f9c16397b2a4e828e699b1c3e657d96/gnosis/eth/clients/etherscan_client.py#L24
https://github.com/safe-global/safe-eth-py/blob/324a5d0e7f9c16397b2a4e828e699b1c3e657d96/gnosis/eth/clients/etherscan_client.py#L66

I'd say remove the API extension and leave the ETHERSCAN_URL like is in [BlockScoutClient](https://github.com/safe-global/safe-eth-py/blob/2ec2cc5907018d49e06d9c72ee121b1209467d92/gnosis/eth/clients/blockscout_client.py#L21)

**Comment by Uxio0** [comment]
Maybe we can close this, as we discussed that one url is useful to access the API and other for generating links to the block explorer
