### ISSUE TITLE
[New chain]: Bitrock Testnet

### ISSUE THREAD

**Issue by BCrypto-dev** [safe-global/safe-eth-py#891]
### Summary

I would like to add Bitrock Testnet chain.

### Chain ID

7771

### Chain detail URL

https://chainlist.org/chain/7771

### RPC URL

https://testnet.bit-rock.io

### Blockscout Client URL

https://testnetscan.bit-rock.io/api/v1/graphql

### Version

1.4.1+L2

### Address (Master copy)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy)

0x46f21d22d4cfa3ae2cc34c8a4ffbe2a4b73f994c130ca60760c618e8f9058cea

### Block explorer URL (Master copy)

https://testnetscan.bit-rock.io/tx/0x46f21d22d4cfa3ae2cc34c8a4ffbe2a4b73f994c130ca60760c618e8f9058cea

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xef5ddc117f42101526178c4846a62eec5f163aa64a42a8d196407266eb119135

### Block explorer URL (Proxy factory)

https://testnetscan.bit-rock.io/tx/0xef5ddc117f42101526178c4846a62eec5f163aa64a42a8d196407266eb119135

**Comment by falvaradorodriguez** [comment]
> Validation has failed with the following errors:
> 
> * Blockscout Client URL (https://testnetscan.bit-rock.io/graphiql) not valid.
> 
> Validation failed!❌

The correct URL should be: https://testnetscan.bit-rock.io/api/v1/graphql
