### ISSUE TITLE
[New chain]: Bitrock Mainnet

### ISSUE THREAD

**Issue by BCrypto-dev** [safe-global/safe-eth-py#892]
### Summary

I would like to add Bitrock Mainnet chain.

### Chain ID

7171

### Chain detail URL

https://chainlist.org/chain/7171

### RPC URL

https://brockrpc.io

### Blockscout Client URL

https://explorer.bit-rock.io/api/v1/graphql

### Version

1.4.1+L2

### Address (Master copy)

0x29fcB43b46531BcA003ddC8FCB67FFE91900C762

### Deployment Tx hash (Master copy)

0x66faafb0b681af6165759018df2bd6916010bb01663c1f3a030c44921cbd96f5

### Block explorer URL (Master copy)

https://explorer.bit-rock.io/tx/0x66faafb0b681af6165759018df2bd6916010bb01663c1f3a030c44921cbd96f5

### Address (Proxy factory)

0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

### Deployment Tx hash (Proxy factory)

0xfabbd11b600aac83203b0800617033b32208a16645bdb81c6a11486c780e665f

### Block explorer URL (Proxy factory)

https://explorer.bit-rock.io/tx/0xfabbd11b600aac83203b0800617033b32208a16645bdb81c6a11486c780e665f

**Comment by falvaradorodriguez** [comment]
> Validation has failed with the following errors:
> 
> * Blockscout Client URL (https://explorer.bit-rock.io/graphiql) not valid.
> 
> Validation failed!❌

The correct url should be: https://explorer.bit-rock.io/api/v1/graphql
