### ISSUE TITLE
[New chain]: Morph Holesky

### ISSUE THREAD

**Issue by DenSmolonski** [safe-global/safe-eth-py#970]
### Summary

I would like to add Morph Holesky chain

### Chain ID

2810

### Chain detail URL

https://chainlist.org/chain/2810

### RPC URL

https://rpc-holesky.morphl2.io/

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Deployment Tx hash (Master copy)

0x75973e7f72dabbd05dfdb748e66935f8e373b6c1cd12515a12590c09d13348c0

### Block explorer URL (Master copy)

https://explorer-holesky.morphl2.io/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938?tab=internal_txns

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Deployment Tx hash (Master copy L2)

0x94c3b3f131f26f5b94bd54de329aa61cb3be71f254295d4ddbbec98fee7ec569

### Block explorer URL (Master copy L2)

https://explorer-holesky.morphl2.io/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA?tab=contract

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x2460996ec48cda803479a8d7959b68325a2a41c16f103b0ee6b2a59103496f13

### Block explorer URL (Proxy factory)

https://explorer-holesky.morphl2.io/address/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC?tab=contract

**Comment by falvaradorodriguez** [comment]
@DenSmolonski Can you check the URL of Blockscout Client? It is not a required field, if it does not exist, you can skip it. Thanks

**Comment by DenSmolonski** [comment]
@falvaradorodriguez Thank you for feedback. I just removed Blockscout Client.
