### ISSUE TITLE
[New chain]: REDSTONE

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-eth-py#993]
### Summary

- https://github.com/safe-global/safe-eth-py/issues/955
- https://github.com/safe-global/safe-eth-py/pull/961
- https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-690.json

### Chain ID

690

### Chain detail URL

https://chainlist.org/chain/690

### RPC URL

https://rpc.redstonechain.com

### Blockscout Client URL

https://explorer.redstone.xyz/api/v1/graphql

### Version

1.3.0

### Address (Master copy)

0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Address (Master copy L2)

0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

### Address (Proxy factory)

0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC

### Deployment Tx hash (Proxy factory)

0x9aebfbb9b29160aa797c78f496770c9a5da4c00565e6b837dde1bcb6116191f5

**Comment by ElvisKrop** [comment]
Hello @falvaradorodriguez :wave: 
Unfortunately, there is no deployment tx hash for both Master copy contracts, because both of them were deployed at GENESIS block. Shall I open a PR for it?

**Comment by falvaradorodriguez** [comment]
> Hello @falvaradorodriguez 👋 Unfortunately, there is no deployment tx hash for both Master copy contracts, because both of them were deployed at GENESIS block. Shall I open a PR for it?

Yes please, in this case the automatic process to validate and create PR will not work. Thanks and sorry for the inconvenience.
